/* eslint-disable */
/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/env.d.ts` (hash: 2118672e85a5a9b3dc89d6bbc3b77f24)
// RATE_LIMITER/ASSETS/API_KEY/ENVIRONMENT are hand-authored to match wrangler's
// output shape; `wrangler types` reconciles them once the bindings are declared
// in wrangler.jsonc.
interface __BaseEnv_Env {
	API_KEY: string;
	ENVIRONMENT: string;
	ASSETS: Fetcher;
	RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}

declare namespace App {
	interface Locals {
		/** Per-request CSP nonce set by middleware for the island script tag. */
		cspNonce: string;
	}
}
