name: Minify HTML, CSS, and JS

on:
  push:
    branches:
      - main
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - '!**.min.**'  # Skip already minified files
  workflow_dispatch:  # Manual trigger option

# Ensure we don't have multiple minification runs at once
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  minify:
    # Run on merges from development branch, handling both CLI and PR merge messages
    if: (contains(github.event.head_commit.message, 'Merge branch') || contains(github.event.head_commit.message, 'Merge pull request')) && contains(github.event.head_commit.message, 'development')
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging runs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pin to specific version
        with:
          fetch-depth: 1  # Shallow clone for efficiency

      - name: Set up Minify Action
        id: minify-setup
        uses: amireshoon/minifyAction@v1.0  # Pin to specific version
        with:
          repo: ${{ github.repository }}

      - name: Run minification script
        id: minify
        run: |
          if [ ! -f minifier.sh ]; then
            echo "::error::minifier.sh not found"
            exit 1
          fi
          chmod +x minifier.sh
          ./minifier.sh ${{ github.repository }}
        continue-on-error: false

      - name: Commit and push minified files
        if: success()  # Only run if previous steps succeeded
        uses: actions-js/push@v1.3  # Pin to specific version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: github/workspace
          branch: main
          message: "chore: minify assets from ${{ github.sha }}"
          author_name: "MinifyAction[bot]"
          author_email: "minify-bot@users.noreply.github.com"
          force: true

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: '❌ Minification failed. Please check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            })
